# github
# name: æ‰“åŒ…Reacté¡¹ç›®
# on: push

# permissions:
#   contents: write

# jobs:
#   npm-build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: è¯»å–ä»“åº“å†…å®¹
#         uses: actions/checkout@v4

#       - name: å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…é¡¹ç›®
#         run: |
#           npm install
#           npm run build

#       - name: éƒ¨ç½²ğŸ™…â€
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: gh-pages
#           folder: build

# Dockerfile
name: æ„å»ºé•œåƒå¹¶æ¨é€åˆ°Docker Hub
on: push

jobs:
  npm-build:
    name: npm-buildå·¥ä½œ
    runs-on: ubuntu-latest

    steps:
      - name: è¯»å–ä»“åº“å†…å®¹
        uses: actions/checkout@v4

      - name: ç™»å½•Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCLER_HUB_USERNAME }}
          password: ${{ secrets.DOCLER_HUB_TOKEN }}

      - name: æ„å»ºå¹¶æ¨é€Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tinshima/react-app:latest
